### ISSUE TITLE
Support for more than two levels of a categorical IV

### ISSUE THREAD

**Issue by devgill15** [mvuorre/bmlm#11]
This is the first time I've posted an issue, so apologies if this is not the appropriate venue.  I have a categorical predictor with more than two levels.  The number of dummy codes necessary is k-1, and those codes need to be included in the model.  Below is my intuitive or simplistic attempt to implement two dummy codes.  Thanks so much for any insight!

`fit.new <- mlm(d = v2,
               id = "ID",
               x = c("L_M", "L_H"),
               m = "awe_cw",
               y = "z.d.r")`

**Comment by mvuorre** [comment]
Hi, thanks for getting in touch, this is certainly the appropriate venue for this question.

Unfortunately, bmlm does not currently support categorical predictors with more than two levels--and I don't have the time to implement this feature. (And so the syntax in your example won't work.)

**Comment by devgill15** [comment]
Thanks for the response, Matt.  This is a great package and I'm looking forward to using it in the future.
