### ISSUE TITLE
Two mediators?

### ISSUE THREAD

**Issue by RachelFreedSussman** [mvuorre/bmlm#14]
Hi,

Thanks for writing such a helpful package. I'm wondering, would this package be able to handle parallel mediation with two mediators? If so, how? If not, do you know of any other packages that would?

Thanks in advance,
Rachel

**Comment by mvuorre** [comment]
You can run any kind of mediation model, multilevel or otherwise, with observed variables using the brms package: <https://github.com/paul-buerkner/brms/>. 

I recently did a workshop where this was covered: <https://mvuorre.github.io/brms-workshop/posts/mediation/>

**Comment by RachelFreedSussman** [comment]
Thank you so much for your quick reply and helpful suggestions!
