### ISSUE TITLE
Is there some metrics can help me to decide this model is suitable or not, just like p-value?

### ISSUE THREAD

**Issue by sixone11** [mvuorre/bmlm#17]
Dear author,

Thank you for your work on the mediation effects research.

Now I am little bit confused about the results getting from the bmlm package.
I tried different datasets, each time it will give me a model. Is there some metrics can help me to decide this model is suitable or not, just like p-value?

Thanks in advance!

Best regards,

Vivian

**Comment by mvuorre** [comment]
Hi Vivian,

We do an extremely brief intro to bayesian inference in the paper (Vuorre & Bolger). I recommend the following books (in order) for beginning students of probabilistic inference:

- Kruschke, J. K. (2014). Doing Bayesian Data Analysis: A Tutorial Introduction with R (2nd Edition). Academic Press.
- McElreath, R. (2020). Statistical rethinking: A Bayesian course with examples in R and Stan (2nd ed.). Taylor and Francis, CRC Press.
- Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., & Rubin, D. B. (2013). Bayesian Data Analysis, Third Edition. Chapman and Hall/CRC.

**Comment by sixone11** [comment]
您的邮件我已收到，会尽快处理。祝好。

**Comment by sixone11** [comment]
您的邮件我已收到，会尽快处理。祝好。
