### ISSUE TITLE
Error in instaling the package

### ISSUE THREAD

**Issue by ozgeugurlu** [mvuorre/bmlm#26]
I followed the procedure outlined below: 

install.packages("devtools")
library(devtools)
# Install from GitHub using the devtools package
devtools::install_github("mvuorre/bmlm", args = "--preclean")

This is the error I got: 

Arguments in `...` must be used.
✖ Problematic argument:
• args = "--preclean"
ℹ Did you misspell an argument name?

How do we fix it?

**Comment by ozgeugurlu** [comment]
I also downloaded install.packages("Rcpp", dependencies = TRUE) previously, and still cannot run the code.

**Comment by mvuorre** [comment]
Thanks, fixed in https://github.com/mvuorre/bmlm/commit/bb7fe2077d22d20507a2e4d995ce5c8ee7106578: use `remotes::install_github("mvuorre/bmlm")`.
