### ISSUE TITLE
Implement binary mediators

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/bmlm#4]

**Comment by CarinaFo** [comment]
Hello Matthi,

thank you for this great package. I was wondering if I can use your package, if I have a binary mediator and a factorial variable as a independent variable (stimulus intensities). I used the mediation package in R before, where you can specify control and treatment values and thus compare different factors. I would however prefer the bayesian hierachichal mediation version :)

**Comment by mvuorre** [comment]
Hi, you cannot do either i) binary mediators (such that they would be appropriately treated as binomial in the other path) or ii) categorical x with more than 2 levels, with bmlm. I'm unlikely to implement this change to bmlm, because you can already easily fit that model with the [brms](https://github.com/paul-buerkner/brms/) package.

Say you have x (categorical with many levels), binary m, and continuous y, with brms syntax you'd fit the model as something like:

```
brm(bf(y ~ x + m) + bf(m ~ x, family = bernoulli()) + set_rescor(FALSE))
```

I don't have time now to verify the above code but it should give you an idea.

I'm closing this issue as this feature is superseded by the brms package.
