### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/bmlm#5]
Currently, bmlm does not pass build cleanly, as detailed in [cran-comments.md](https://github.com/mvuorre/bmlm/blob/dev/cran-comments.md). I would like to get it to CRAN but am afraid it wont go through with the warnings.
## Test environments

```
local OS X install, R 3.3.1
win-builder (devel and release)
```
### R CMD check results

0 errors | 1 warning | 0 notes

Status: 1 WARNING checking compiled code ... WARNING

File ‘bmlm/libs/bmlm.so’:
Found ‘___assert_rtn’, possibly from ‘assert’ (C)
Object: ‘Modules.o’

Compiled code should not call entry points which might terminate R nor write to stdout/stderr instead of to the console, nor the system RNG.
### Win-builder results

Installation time in seconds: 197 Check time in seconds: 108 Status: 1 WARNING

```
checking whether package 'bmlm' can be installed ... WARNING
```

Found the following significant warnings:

d:/RCompile/CRANpkg/lib/3.4/BH/include/boost/math/special_functions/detail/bernoulli_details.hpp:127:36: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]

d:/RCompile/CRANpkg/lib/3.4/BH/include/boost/math/special_functions/detail/bernoulli_details.hpp:151:9: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]

See 'd:/RCompile/CRANguest/R-devel/bmlm.Rcheck/00install.out' for details.

Kindly asking if @jgabry has insight on these, what I think are C++ and rstanarm related issues.

**Comment by jgabry** [comment]
Hey Matti, I should be able to take a look tonight or tomorrow and help
you sort it out. And yeah, definitely hold off on submitting to CRAN until
we deal with this.

Jonah

**Comment by jgabry** [comment]
I haven't fully sorted it out yet. @bgoodri have you seen this check error
from a package made with rstan.package.skeleton? Looks like maybe something
to do with the shared object but I haven't seen this before.

On another note, unless I missed them the package doesn't seem to have
any unit tests. I would be very hesitant about releasing a package on
CRAN until you have a pretty thorough and public testing framework.  I
can't recommend that enough.

Jonah

**Comment by bgoodri** [comment]
I have seen the -Wlong-long warning on Windows and we had to put CXX_STD =
CXX11 into src/Makevars.win to build it with the C++11 standard. I have not
seen the OSX one, but I don't use OSX. What version of clang++ is it and
what optimization level?

**Comment by mvuorre** [comment]
Thanks, both of you!
1. **Wlong-long** warning with win-builder: I added the `src/Makevars.win` as in rstanarm (with CXX_STD = CXX11), and I no longer get the warning with win-builder. 👍 
2. clang version on my OS X:

```
> clang++ --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I don't know how to answer the question about clang optimization level. The OS X warning might be related to [this discussion](https://github.com/airoldilab/sgd/issues/44).

(I am currently writing tests and hoping to add them soon. Thanks for this suggestion!)

**Comment by mvuorre** [comment]
I have reproduced the OS X warning on a newer system (mac OS Sierra)

```
> clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by bgoodri** [comment]
You have `-DBOOST_DISABLE_ASSERTS` in the `PKG_CPPFLAGS` line in the src/Makevars file. @jgabry can you run R CMD check on the dev branch of bmlm?

**Comment by jgabry** [comment]
Yeah I can do it this evening. I'll get back to you.

**Comment by jgabry** [comment]
@bgoodri for me the dev branch passes R CMD check

**Comment by bgoodri** [comment]
OK. Then I would suspect another copy of Boost is lurking on the original
computer that somehow gets pulled in instead of BH.

**Comment by mvuorre** [comment]
OK, it seems like its a local problem on my 2 machines then. I'll investigate and close this issue once I figure out what is causing the warnings.

Thank you both so much!

**Comment by mvuorre** [comment]
I can't replicate the issue on other than my personal computers, so it seems that it's a local problem with C++ / Boost. The issue with the package is therefore resolved.
