### ISSUE TITLE
Implement multiple mediators

### ISSUE THREAD

**Issue by davidfoxcroft** [mvuorre/bmlm#7]
It would be great to have X - m1 & m2 & m3.... - Y. Also multiple predictors. As in sem.

**Comment by mvuorre** [comment]
Hi, and thank you very much for the suggestion! I'm planning on implementing multiple mediators at some point, but not necessarily very soon. However, the package isn't aimed to be a fully flexible SEM package, so if you are looking beyond a multiple mediators model, I'd suggest coding the model manually in Stan. bmlm's Stan code should provide guidance.
