### ISSUE TITLE
Support covariates

### ISSUE THREAD

**Issue by jacob-long** [mvuorre/bmlm#9]
Great work on this package. I think this would be perfect for fields that use panel survey data (like mine!) if it supported more straightforward inclusion of covariates in the model, which understandably are less necessary in psychology and other primarily experimental fields. 

For now, the generated Stan code makes a useful template for adding on covariates but I suspect it may not be hard to program in support for them.

**Comment by mvuorre** [comment]
Thanks for the feedback. I'm planning to include covariates in a future major release, but I don't know when I will get around to working on it. The main reason for not including them so far is that they are less relevant in cog. psych / neuro studies, which I had in mind when designing this.

Do you think covariates are more common / important for the a or b paths?

**Comment by jacob-long** [comment]
I would say the default practice is for the same set of covariates to be used for both of the regression models unless there is some compelling reason to specify each one differently. In my project I'm working on, I provide a covariates matrix and use the same matrix in both regressions for simplicity. Obviously each regression still has a different vector of coefficients for the covariates.

**Comment by mvuorre** [comment]
Great, thank you. I will keep this in mind if/when we add support for covariates in the model.

**Comment by mvuorre** [comment]
For anyone who happens to find this issue: Please use brms instead: https://mvuorre.github.io/brms-workshop/posts/mediation/slides.html#30
